import { apiRequest, APIError, setAccessToken } from './apiClient';
export { APIError };
export const studentAPI={searchHostels:async(query:string,filters:Record<string,any>={})=>{const p=new URLSearchParams();if(query)p.set('q',query);if(filters.city)p.set('city',filters.city);const r=await apiRequest<any>(`/api/v1/properties?${p}`);return r.data||[];},searchByImage:async(_file:File)=>({results:[],message:'Image search requires a configured AI vision provider.'}),getHostelDetails:async(id:string)=>{const r=await apiRequest<any>(`/api/v1/properties/${id}`);return r.data;},getHostelReviews:async(id:string)=>{const r=await apiRequest<any>(`/api/v1/reviews/${id}`);return r.data||[];},bookHostel:async(id:string,d:Record<string,any>)=>{const r=await apiRequest<any>('/api/v1/bookings',{method:'POST',body:JSON.stringify({propertyId:id,roomId:d.roomId,visitDate:d.visitDate,message:d.message})});return r.data;},getRentPayments:async(_id:string)=>{const r=await apiRequest<any>('/api/v1/payments/mine');return r.data||[];},getProfile:async(_id:string)=>{const r=await apiRequest<any>('/api/v1/me');return r.data;}};
export const ownerAPI={getProperties:async(_id:string)=>{const r=await apiRequest<any>('/api/v1/properties/owner');return r.data||[];},createProperty:async(d:Record<string,any>)=>{const r=await apiRequest<any>('/api/v1/properties',{method:'POST',body:JSON.stringify(d)});return r.data;},updateProperty:async(id:string,d:Record<string,any>)=>{const r=await apiRequest<any>(`/api/v1/properties/${id}`,{method:'PATCH',body:JSON.stringify(d)});return r.data;},deleteProperty:async(_id:string)=>({success:false,message:'Use property suspension/soft-delete workflow before deletion is enabled.'}),getPropertyRooms:async(id:string)=>{const r=await apiRequest<any>(`/api/v1/properties/${id}/rooms`);return r.data||[];},getPropertyTenants:async(_id:string)=>[],addTenant:async()=>{throw new Error('Tenant endpoint is not yet connected.');},getBookingRequests:async(_id:string)=>{const r=await apiRequest<any>('/api/v1/bookings/owner');return r.data||[];},respondToBooking:async(id:string,status:'approved'|'rejected',d:Record<string,any>={})=>{const r=await apiRequest<any>(`/api/v1/bookings/${id}/status`,{method:'PATCH',body:JSON.stringify({status,roomId:d.roomId})});return r.data;},getPaymentAccounts:async(_id:string)=>[],addPaymentAccount:async()=>{throw new Error('Owner payment-account endpoint requires banking provider integration.');},getProfile:async(_id:string)=>{const r=await apiRequest<any>('/api/v1/me');return r.data;},updateProfile:async(_id:string,d:Record<string,any>)=>{const r=await apiRequest<any>('/api/v1/me',{method:'PATCH',body:JSON.stringify(d)});return r.data;}};
export const authAPI={studentLogin:async(e:string,p:string)=>login(e,p),ownerLogin:async(e:string,p:string)=>login(e,p),studentSignup:async(d:Record<string,any>)=>register({...d,role:'student'}),ownerSignup:async(d:Record<string,any>)=>register({...d,role:'owner'}),googleLogin:async()=>{throw new Error('Google OAuth requires provider credentials.');},logout:async()=>{setAccessToken(null);return{success:true};},verifyToken:async()=>{try{await apiRequest('/api/v1/me');return{valid:true};}catch{return{valid:false};}},refreshToken:async()=>{throw new Error('Refresh token rotation is not enabled yet.');},forgotPassword:async()=>({message:'Configure an email provider before enabling password reset.'}),resetPassword:async()=>({success:false,message:'Password reset endpoint is not enabled yet.'})};
async function login(email:string,password:string){const r=await apiRequest<any>('/api/v1/auth/login',{method:'POST',body:JSON.stringify({email,password})});setAccessToken(r.data.token);return r.data;}async function register(d:Record<string,any>){const r=await apiRequest<any>('/api/v1/auth/register',{method:'POST',body:JSON.stringify(d)});setAccessToken(r.data.token);return r.data;}
export const paymentAPI={initializePayment:async(amount:number,description:string)=>{const r=await apiRequest<any>('/api/v1/payments/initialize',{method:'POST',body:JSON.stringify({amount,description})});return r.data;},verifyPayment:async(paymentId:string,_signature:string)=>({verified:false,paymentId,message:'Payment must be verified by the configured gateway webhook.'})};
export const aiServices={extractRoomFeatures:async()=>({features:[],message:'Configure an AI vision provider.'}),getRecommendations:async()=>{const r=await apiRequest<any>('/api/v1/properties');return(r.data||[]).slice(0,3);},processUserQuery:async(query:string)=>({query,intent:'search',preferences:{query}})};
export async function handleAPIResponse(response:Response){const d=await response.json().catch(()=>({}));if(!response.ok)throw new APIError(response.status,d?.error?.message||'API Error',d);return d;}
