const API_BASE = (import.meta.env.VITE_API_URL || "http://localhost:8080").replace(/\/$/, "");
const TOKEN_KEY = "auth_token";
export class APIError extends Error { constructor(public status:number, public data:any){super(data?.message||"API request failed");} }
async function request<T>(path:string, options:RequestInit={}):Promise<T>{const headers=new Headers(options.headers);if(options.body&&!headers.has("Content-Type"))headers.set("Content-Type","application/json");const token=localStorage.getItem(TOKEN_KEY);if(token)headers.set("Authorization",`Bearer ${token}`);const response=await fetch(`${API_BASE}${path}`,{...options,headers});const data=await response.json().catch(()=>({}));if(!response.ok)throw new APIError(response.status,data);return data as T;}
const qs=(params:Record<string,any>)=>{const q=new URLSearchParams();Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=="")q.set(k,String(v));});const s=q.toString();return s?`?${s}`:"";};
export const studentAPI={searchHostels:(query:string,filters:Record<string,any>={})=>request<{results:any[]}>(`/api/hostels${qs({q:query,...filters})}`),searchByImage:async(_file:File)=>({results:[],message:"Image search requires an AI provider configuration."}),getHostelDetails:(id:string)=>request<any>(`/api/hostels/${id}`),getHostelReviews:async(_id:string)=>({results:[]}),bookHostel:(propertyId:string,data:Record<string,any>)=>request<any>("/api/bookings",{method:"POST",body:JSON.stringify({propertyId,...data})}),getBookings:()=>request<{results:any[]}>("/api/bookings"),cancelBooking:(id:string)=>request<any>(`/api/bookings/${id}`,{method:"PATCH",body:JSON.stringify({status:"cancelled"})}),getRentPayments:(_id:string)=>request<{results:any[]}>("/api/payments"),getProfile:()=>request<any>("/api/auth/me")};
export const ownerAPI={getProperties:(_id?:string)=>request<{results:any[]}>("/api/owner/properties"),createProperty:(data:Record<string,any>)=>request<any>("/api/owner/properties",{method:"POST",body:JSON.stringify(data)}),updateProperty:(id:string,data:Record<string,any>)=>request<any>(`/api/owner/properties/${id}`,{method:"PATCH",body:JSON.stringify(data)}),deleteProperty:(id:string)=>request<any>(`/api/owner/properties/${id}`,{method:"DELETE"}),getPropertyRooms:(id:string)=>request<{results:any[]}>(`/api/owner/properties/${id}/rooms`),getPropertyTenants:async(_id:string)=>({results:[]}),addTenant:async(_id:string,_data:Record<string,any>)=>{throw new APIError(501,{message:"Tenant management API is being completed."});},getBookingRequests:()=>request<{results:any[]}>("/api/bookings"),respondToBooking:(id:string,status:"approved"|"rejected",data:Record<string,any>={})=>request<any>(`/api/bookings/${id}`,{method:"PATCH",body:JSON.stringify({...data,status:status==="approved"?"accepted":"rejected"})}),getPaymentAccounts:async()=>({results:[]}),addPaymentAccount:async()=>{throw new APIError(501,{message:"Payment account API is being completed."});},getProfile:()=>request<any>("/api/auth/me"),updateProfile:(_id:string,data:Record<string,any>)=>request<any>("/api/auth/profile",{method:"PATCH",body:JSON.stringify(data)})};
export const authAPI={studentLogin:(email:string,password:string)=>request<any>("/api/auth/login",{method:"POST",body:JSON.stringify({email,password})}),studentSignup:(data:Record<string,any>)=>request<any>("/api/auth/signup",{method:"POST",body:JSON.stringify({...data,name:data.name||data.fullName,role:"student"})}),ownerLogin:(email:string,password:string)=>request<any>("/api/auth/login",{method:"POST",body:JSON.stringify({email,password})}),ownerSignup:(data:Record<string,any>)=>request<any>("/api/auth/signup",{method:"POST",body:JSON.stringify({...data,name:data.name||data.fullName,role:"owner"})}),googleLogin:async()=>{throw new APIError(501,{message:"Google OAuth is not configured."});},logout:async()=>{localStorage.removeItem(TOKEN_KEY);localStorage.removeItem("userData");return{success:true};},verifyToken:()=>request<any>("/api/auth/me"),refreshToken:async()=>{throw new APIError(501,{message:"Token refresh is not configured."});},forgotPassword:async()=>{throw new APIError(501,{message:"Password reset email service is not configured."});},resetPassword:async()=>{throw new APIError(501,{message:"Password reset service is not configured."});}};
export const paymentAPI={initializePayment:(amount:number,description:string)=>request<any>("/api/payments/order",{method:"POST",body:JSON.stringify({amount,description})}),verifyPayment:(paymentId:string,signature:string)=>request<any>("/api/payments/verify",{method:"POST",body:JSON.stringify({paymentId,signature})})};
export const aiServices={extractRoomFeatures:async()=>({features:[],message:"AI provider is not configured."}),getRecommendations:(preferences:Record<string,any>)=>studentAPI.searchHostels("",preferences),processUserQuery:async(query:string)=>({query,intent:"search",preferences:{}})};
export async function handleAPIResponse(response:Response){const data=await response.json().catch(()=>({}));if(!response.ok)throw new APIError(response.status,data);return data;}
