import express, { type ErrorRequestHandler } from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { env } from './config/env.js';
import authRoutes from './routes/auth.routes.js';
import propertyRoutes from './routes/property.routes.js';
import bookingRoutes from './routes/booking.routes.js';
import reviewRoutes from './routes/review.routes.js';
import meRoutes from './routes/me.routes.js';
import adminRoutes from './routes/admin.routes.js';

const app=express();
app.disable('x-powered-by');
app.set('trust proxy',1);
app.use(helmet());
app.use(cors({origin:env.FRONTEND_URL,credentials:true}));
app.use(express.json({limit:'1mb'}));
app.use(express.urlencoded({extended:false,limit:'1mb'}));
app.get('/api/v1/health',(_req,res)=>res.json({success:true,service:'student-hostel-platform-api',status:'ok',timestamp:new Date().toISOString()}));
app.use('/api/v1/auth',authRoutes);
app.use('/api/v1/properties',propertyRoutes);
app.use('/api/v1/bookings',bookingRoutes);
app.use('/api/v1/reviews',reviewRoutes);
app.use('/api/v1/me',meRoutes);
app.use('/api/v1/admin',adminRoutes);
app.use((_req,res)=>res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'The requested API endpoint does not exist.'}}));
const errorHandler:ErrorRequestHandler=(error,_req,res,_next)=>{console.error(error);if(error?.name==='ZodError')return res.status(400).json({success:false,error:{code:'VALIDATION_ERROR',message:'Invalid request data.',details:error.issues}});res.status(500).json({success:false,error:{code:'INTERNAL_SERVER_ERROR',message:env.NODE_ENV==='production'?'An unexpected error occurred.':error instanceof Error?error.message:'Unknown error'}});};
app.use(errorHandler);
export default app;
