import { useEffect,useState } from 'react';
import { Navigate,useNavigate } from 'react-router-dom';
import { Users,Building2,CalendarCheck,IndianRupee,ShieldAlert,LogOut,RefreshCw,CheckCircle2,XCircle,Activity,FileClock } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { API_BASE_URL } from '@/lib/backend';
async function adminApi(path:string,options:RequestInit={}){const token=localStorage.getItem('admin_token');const r=await fetch(`${API_BASE_URL}/api/admin${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.message||'Request failed');return d;}
export default function AdminDashboard(){const nav=useNavigate();const token=localStorage.getItem('admin_token');const [data,setData]=useState<any>(null);const [rows,setRows]=useState<any[]>([]);const [tab,setTab]=useState('overview');const [error,setError]=useState('');
const load=async()=>{try{setError('');if(tab==='overview'){setData(await adminApi('/overview'));return;}if(tab==='analytics'){setData(await adminApi('/analytics'));return;}const path=tab==='properties'?'/properties':tab==='users'?'/users':tab==='bookings'?'/bookings':tab==='payments'?'/payments':'/audit-logs';setRows((await adminApi(path)).results||[]);}catch(e){setError(e instanceof Error?e.message:'Unable to load dashboard');}};useEffect(()=>{if(token)load();},[tab]);if(!token)return <Navigate to="/admin/login" replace/>;const logout=()=>{localStorage.removeItem('admin_token');localStorage.removeItem('admin_user');nav('/admin/login',{replace:true});};const verify=async(id:string,status:string)=>{await adminApi(`/properties/${id}`,{method:'PATCH',body:JSON.stringify({status})});load();};const toggleUser=async(u:any)=>{await adminApi(`/users/${u.id}`,{method:'PATCH',body:JSON.stringify({isActive:!u.is_active})});load();};const tabs=['overview','analytics','properties','users','bookings','payments','audit'];
return <div className="min-h-screen bg-slate-50"><header className="sticky top-0 z-20 border-b bg-white/95 backdrop-blur"><div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between"><div><h1 className="font-bold text-xl">Residential Nexus <span className="text-primary">Admin</span></h1><p className="text-xs text-muted-foreground">Secure platform control center</p></div><Button variant="outline" onClick={logout}><LogOut className="size-4 mr-2"/>Logout</Button></div></header><main className="max-w-7xl mx-auto p-6 space-y-6">{error&&<div className="rounded-xl bg-red-50 text-red-700 p-3">{error}</div>}<div className="flex gap-2 flex-wrap">{tabs.map(x=><Button key={x} variant={tab===x?'default':'outline'} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</Button>)}<Button variant="ghost" onClick={load}><RefreshCw className="size-4 mr-2"/>Refresh</Button></div>
{tab==='overview'&&data&&<><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{[[Users,'Users',data.metrics.users],[Users,'Students',data.metrics.students],[Building2,'Properties',data.metrics.properties],[IndianRupee,'Revenue',`₹${data.metrics.revenue.toLocaleString('en-IN')}`],[CalendarCheck,'Bookings',data.metrics.bookings],[ShieldAlert,'Pending Properties',data.metrics.pendingProperties],[Activity,'Pending Bookings',data.metrics.pendingBookings],[IndianRupee,'Payments',data.metrics.payments]].map(([I,l,v]:any)=><div key={l} className="rounded-2xl bg-white border p-5"><I className="size-5 text-primary mb-4"/><p className="text-sm text-muted-foreground">{l}</p><p className="text-2xl font-bold mt-1">{v}</p></div>)}</div><section className="bg-white rounded-2xl border p-5"><h2 className="font-semibold mb-4">Recent users</h2>{data.recentUsers.map((u:any)=><div key={u.id} className="flex justify-between py-3 border-b last:border-0"><span>{u.name}<span className="text-xs text-muted-foreground ml-2">{u.email}</span></span><span className="text-xs rounded-full bg-slate-100 px-2 py-1">{u.role}</span></div>)}</section></>}
{tab==='analytics'&&data&&<div className="grid md:grid-cols-2 gap-5">{[['User growth',data.usersByMonth],['Booking status',data.bookingsByStatus],['Payment status',data.paymentsByStatus],['Properties by city',data.propertiesByCity]].map(([title,list]:any)=><section key={title} className="bg-white rounded-2xl border p-5"><h2 className="font-semibold mb-4">{title}</h2>{list?.map((x:any)=><div key={x.label} className="flex justify-between py-2 border-b last:border-0 text-sm"><span>{x.label}</span><b>{x.value}{x.total!==undefined?` · ₹${Number(x.total).toLocaleString('en-IN')}`:''}</b></div>)}</section>)}</div>}
{tab==='properties'&&<section className="bg-white rounded-2xl border overflow-hidden"><div className="p-5 border-b"><h2 className="font-semibold">Property verification</h2></div><div className="divide-y">{rows.map(p=><div key={p.id} className="p-5 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><p className="font-semibold">{p.name}</p><p className="text-sm text-muted-foreground">{p.owner_name} · {p.city} · {p.beds} beds / {p.occupied} occupied</p></div><div className="flex items-center gap-2"><span className="text-xs px-2 py-1 rounded-full bg-slate-100">{p.verification_status}</span>{p.verification_status!=='approved'&&<Button size="sm" onClick={()=>verify(p.id,'approved')}><CheckCircle2 className="size-4 mr-1"/>Approve</Button>}{p.verification_status!=='rejected'&&<Button size="sm" variant="outline" onClick={()=>verify(p.id,'rejected')}><XCircle className="size-4 mr-1"/>Reject</Button>}</div></div>)}</div></section>}
{tab==='users'&&<section className="bg-white rounded-2xl border overflow-hidden"><div className="p-5 border-b"><h2 className="font-semibold">User management</h2></div><div className="divide-y">{rows.map(u=><div key={u.id} className="p-5 flex items-center justify-between gap-4"><div><p className="font-semibold">{u.name}</p><p className="text-sm text-muted-foreground">{u.email} · {u.role}</p></div><Button size="sm" variant={u.is_active?'outline':'default'} onClick={()=>toggleUser(u)}>{u.is_active?'Disable':'Enable'}</Button></div>)}</div></section>}
{tab==='bookings'&&<DataTable title="Bookings" rows={rows} fields={['student_name','student_email','property_name','owner_name','status','visit_at']}/>} {tab==='payments'&&<DataTable title="Payments" rows={rows} fields={['student_name','student_email','property_name','amount','status','provider','paid_at']}/>} {tab==='audit'&&<DataTable title="Security audit log" rows={rows} fields={['created_at','admin_email','action','entity_type','entity_id']}/>}</main></div>}
function DataTable({title,rows,fields}:{title:string,rows:any[],fields:string[]}){return <section className="bg-white rounded-2xl border overflow-auto"><div className="p-5 border-b flex items-center gap-2"><FileClock className="size-5 text-primary"/><h2 className="font-semibold">{title}</h2></div><table className="w-full text-sm"><thead><tr className="bg-slate-50">{fields.map(f=><th key={f} className="text-left p-3 whitespace-nowrap">{f.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i} className="border-t">{fields.map(f=><td key={f} className="p-3 whitespace-nowrap">{r[f]===null||r[f]===undefined?'—':String(r[f])}</td>)}</tr>)}</tbody></table></section>}
